# use Ganache's forked mainnet mode as the default network
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts v3.0.0
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.0.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.0.0"
networks:
  default: mainnet-fork
  mainnet-fork:
    weth: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  kovan:
    weth: "0xd0a1e359811322d97991e03f863a0c30c2cf029c"
  mainnet:
    weth: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  mumbai:
    wmatic: "0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889"
  matic:
    wmatic: "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"

wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}
